config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get '/genre_items' => 'items#genre_items'
    end
    resource :customers, only: [:show, :edit, :update] do
      get '/confirm' => 'customers#confirm'
      patch '/deleted' => 'customers#deleted'
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get "orders/confirm" => "orders#new"
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, except: [:new, :show]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  validates :name, presence:true
  validates :introduction, presence:true
  validates :price, presence:true
  validates :sale_status, inclusion: {in: [true, false] }

  has_one_attached :item_image

  def get_item_image
    (item_image.attached?) ? item_image : 'no_image.jpg'
  end

  def add_tax_price
    (self.price*1.10).round
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin_application'

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品の登録に失敗しました"
      @genres = Genre.all
      @item = Item.new
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品登録情報を変更しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品登録情報の変更に失敗しました"
      @genres = Genre.all
      @item = Item.new
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :sale_status, :item_image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<strong><%= f.label :item_image, "商品画像", style:"margin-right:70px;" %></strong>
<%= f.file_field :item_image, accept: 'image/*' %><br>

<strong><%= f.label :name, "商品名", style:"margin-right:86px;"  %></strong>
<%= f.text_field :name, placeholder: "商品名",size: "36" %><br>

<strong><%= f.label :introduction, "商品説明", style:"vertical-align:top; margin-top:5px; margin-right:70px;"  %></strong>
<%= f.text_area :introduction, placeholder: "ここに説明文を記述します", style:"width:307px; height:150px; resize:none;" %><br>

<strong><%= f.label :genre_id, "ジャンル", style:"margin-right:70px;"  %></strong>
<%= f.collection_select(:genre_id, genres, :id, :name, { prompt: "--選択してください--" }, {style: "width:307px;"}) %><br>

<strong><%= f.label :price, "税抜価格", style:"margin-right:70px;"  %></strong>
<%= f.text_field :price, placeholder: "1000",size: "36" %><strong>円</strong><br>

<strong><%= f.label :sale_status, "販売ステータス", style:"margin-right:20px;"  %></strong>
<%= f.radio_button :sale_status, "true", checked: true %><span class="mr-4">販売中</span><%= f.radio_button :sale_status, "false" %>販売停止中<br>
<% if local_assigns[:item] %>
  <%= f.submit "新規登録", class:"btn btn-success", style:"font-weight:bold; padding:5px 20px; margin:20px 20px 0 220px;" %>
<% else %>
  <%= f.submit "変更を保存", class:"btn btn-success", style:"font-weight:bold; padding:5px 20px; margin:20px 20px 0 220px;" %>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container">
  <%= flash[:notice] %>
  <h5 class="text-center", style="background-color:#eee; width:120px; margin:30px 0 30px 115px;"><b>商品編集</b></h5>
  <div class="row">
    <div class="col-8 m-auto">
      <div class="col-10">
        <%= form_with model:@item, url: admin_item_path(@item.id) do |f| %>
          <%= render 'form',f: f, genres: @genres  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h5 class="text-center", style="background-color:#eee; width:120px; margin:30px 0 0 115px;"><b>商品一覧</b></h5>
  <%= link_to new_admin_item_path, style:"margin-left:1000px; font-size: 40px; color:#555;" do %>
    <i class="fas fa-plus-circle"></i>
  <% end %>
  <div class="row">
    <div class="col-12">
      <table class="table table-borderless", style="width:950px; margin: 0 auto; border-top:1px solid #bbb;">
        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th></th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td class="align-middle"><%= item.id %></td>
              <td class="align-middle", style="text-decoration:underline">
                <%= link_to admin_item_path(item), class:"text-dark" do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td class="align-middle"><%= item.price.to_s(:delimited) %></td>
              <td class="align-middle"><%= item.genre.name %></td>
              <td width="200px"></td>
              <% if item.sale_status == true %>
                <td class="text-success font-weight-bold">販売中</td>
              <% else %>
                <td class="text-secondary font-weight-bold">販売停止中</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <%= flash[:notice] %>
  <h5 class="text-center", style="background-color:#eee; width:150px; margin:30px 0 30px 100px;"><b>商品新規登録</b></h5>
  <div class="row">
    <div class="col-8 m-auto">
      <div class="col-10">
        <%= form_with model:@item, url: admin_items_path, method: :post do |f| %>
          <%= render 'form', item: @item, f: f, genres: @genres %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <%= flash[:notice] %>
  <h5 class="text-center", style="background-color:#eee; width:120px; margin:30px 0 30px 115px;"><b>商品詳細</b></h5>
  <div class="row mt-5">
    <%= image_tag @item.get_item_image, style:"margin-left:70px;", size:"220x150" %>
    <div class="col-8 m-auto">
      <div class="col-10">
        <table>
          <tbody>
            <tr>
              <td width="140px"><b>商品名</b></td>
              <td width="300px"><%= @item.name %></td>
            </tr>
            <tr>
              <td style="vertical-align: baseline;"><p style="font-weight:bold; margin-top:10px;">商品説明</p></td>
              <td><P style="margin-top:10px;"><%= @item.introduction %><p/></td>
            </tr>
            <tr>
              <td><b>ジャンル</b></td>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td><p style="font-weight:bold; margin-top:10px;">税込価格<br>(税抜価格)</p></td>
              <td><strong><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</strong></td>
            </tr>
            <tr>
              <td><b>販売ステータス</b></td>
              <% if @item.sale_status == true %>
                <td class="text-success font-weight-bold">販売中</td>
              <% else %>
                <td class="text-secondary font-weight-bold">販売停止中</td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <%= link_to "編集する", edit_admin_item_path(@item), class:"w-25 btn btn-success", style:"font-weight:bold; padding:5px 20px; margin:20px 20px 0 120px;" %>
      </div>
    </div>
  </div>
</div>