config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get '/genre_items' => 'items#genre_items'
    end
    resource :customers, only: [:show, :edit, :update] do
      get '/confirm' => 'customers#confirm'
      patch '/deleted' => 'customers#deleted'
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get "orders/confirm" => "orders#new"
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, except: [:new, :show]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :lastname, presence: true
  validates :firstname, presence: true
  validates :kana_lastname, presence: true
  validates :kana_firstname, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :email, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  layout "admin_application"

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:lastname, :firstname, :kana_lastname, :kana_firstname, :postal_code, :address, :tel, :email, :password, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_error_messages.html.erb
<% if customer.errors.any? %>
  <%= customer.errors.count %>件のエラーが発生しました
  <ul>
    <% customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/admin/customers/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10'>
      <h4 class="my-4 text-center", style="background-color: #eee; width:340px; padding-left: 12px;"><b><%= @customer.lastname %><%= @customer.firstname %>さんの会員情報編集</b></h4>

      <%= render 'error_messages', customer: @customer %>

      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>

        <div class="row mb-3">
          <div class="col-2">
            会員ID
          </div>
          <div class="col-4">
            <%= @customer.id %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :name, "氏名" %>
          </div>
          <div class="col-4">
            <%= f.text_field :lastname, class: "form-control" %>
          </div>
          <div class="col-4">
            <%= f.text_field :firstname, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :kana_name, "フリガナ" %>
          </div>
          <div class="col-4">
            <%= f.text_field :kana_lastname, class: "form-control" %>
          </div>
          <div class="col-4">
            <%= f.text_field :kana_firstname, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :postal_code, "郵便番号" %>
          </div>
          <div class="col-4">
            <%= f.text_field :postal_code, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :address, "住所" %>
          </div>
          <div class="col-10">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :tel, "電話番号" %>
          </div>
          <div class="col-4">
            <%= f.text_field :tel, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :email, "メールアドレス" %>
          </div>
          <div class="col-4">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
            <%= f.label :is_deleted, "会員ステータス" %>
          </div>
          <div class="col-4 mt-3">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", class: "text-secondary font-weight-bold" %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", class: "text-secondary font-weight-bold" %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-3">
          </div>
          <div class="col-4">
            <%= f.submit "編集を保存", class: "btn btn-success px-5 mt-3", style:"font-weight:bold;" %>
          </div>
        </div>

      <% end %>



    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8 offset-2'>
      <h4 class="my-4", style="background-color: #eee; width:120px; padding-left: 12px;"><b>会員一覧</b></h4>

        <table class="table">
          <thead>
            <tr class="table-active">
              <th>会員ID</th>
              <th style="text-decoration: underline;">氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <% @customers.each do |customer| %>
          <tbody>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer), style: "color: #000; text-decoration: underline;" do %>
                <%= customer.lastname %><%= customer.firstname %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <% if customer.is_deleted == false %>
                <td class="text-success font-weight-bold">有効</td>
              <% else %>
                <td class="text-secondary font-weight-bold">退会</td>
              <% end %>
            </tr>
          </tbody>
          <% end %>
            <tr>
              <td colspan="4"></td>
            </tr>
        </table>

        <ul class="pagination justify-content-center">
          <%= paginate @customers %>
        </ul>

    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8'>
      <h4 class="my-4 text-center", style="background-color: #eee; width:290px; padding-left: 12px;"><b><%= @customer.lastname %><%= @customer.firstname %>さんの会員詳細</b></h4>
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.lastname %>　<%= @customer.firstname %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.kana_lastname %>　<%= @customer.kana_firstname %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.tel %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <% if @customer.is_deleted == false %>
            <td class="text-success font-weight-bold">有効</td>
          <% else %>
            <td class="text-secondary font-weight-bold">退会</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success px-3", style:"font-weight:bold;" %>
            <%= link_to '注文内容一覧を見る', admin_path, class: "btn btn-primary ml-5", style:"font-weight:bold;" %>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>