config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get '/genre_items' => 'items#genre_items'
    end
    resource :customers, only: [:show, :edit, :update] do
      get '/confirm' => 'customers#confirm'
      patch '/deleted' => 'customers#deleted'
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get "orders/confirm" => "orders#new"
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, except: [:new, :show]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }


  def buy_total
    buy_total = 0
    self.order_details.each do |order_detail|
      buy_total += order_detail.subtotal.to_i
    end
    return buy_total
  end

  def order_items_id
    order_items_id = []
    self.order_details.each do |detail|
      order_items_id.push(detail.item_id)
    end
    return order_items_id
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  layout "admin_application"




  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details

  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      if @order.status == "入金待ち"
        @order_details.update_all(making_status: "着手不可")
      elsif @order.status == "入金確認"
        @order_details.update_all(making_status: "製作待ち")
      end
      redirect_to admin_order_path(@order)
    else
      render "show"
    end
  end



  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class = "ml-5 mt-5 mr-5">
  <div>
    <h5 class = "text-center", style = "background-color:#eee; width:150px; margin-left:100px; font-weight:bold;">注文履歴詳細</h5>
    <table class = "table table-borderless">
      <tbody>
        <tr>
          <td style="width: 10%"><b>購入者</b></td>
          <td style="width: 50%">
            <%= link_to admin_customer_path(@order), class:"text-dark", style:"text-decoration: underline;" do %>
              <%= @order.customer.lastname %><%= @order.customer.firstname %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><b>注文日</b></td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td><b>配送先</b></td>
          <td>〒<%= @order.postal_code %> <%= @order.address %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= @order.shipping_name %></td>
        </tr>
        <tr>
          <td><b>支払い方法</b></td>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <td><b>注文ステータス</b></td>
            <td>
              <%= form_with model: [ :admin, @order ]  do |f| %>
              <%= f.select :status,  Order.statuses.keys.to_a, {} %><%= f.submit "更新", class:"ml-5 btn btn-success", style:"font-weight:bold;" %>
              <% end %>
            </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <div style = "display:inline-block;">
    <table class = "table table-borderless border-bottom border-top mt-5", style = "width:850px; border-color:#eee;" >
      <thead>
        <tr style = "background-color:#f2f2f2;">
          <td style="width: 220px">
            <b>商品名</b>
          </td>
          <td style="width: 180px">
            <b>単価（税込み）</b>
          </td>
          <td style="width: 120px">
            <b>数量</b>
          </td>
          <td style="width: 120px">
            <b>小計</b>
          </td>
          <td style="width: 220px">
            <b>製作ステータス</b>
          </td>
          <td>

          </td>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
        <tr>
          <td>
            <%= order_detail.item.name %>
          </td>
          <td>
            <%= order_detail.tax_price.to_s(:delimited) %>
          </td>
          <td>
            <%= order_detail.amount %>
          </td>
          <td>
            <%= order_detail.subtotal.to_s(:delimited) %>
          </td>
          <td>
            <%= form_with model: [ :admin, order_detail ]  do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a, {} %><%= f.submit "更新", class:"ml-3  btn btn-success", style:"font-weight:bold;" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div class = "ml-5" style = "display:inline-block;">
      <table class = "table table-borderless">
        <tr>
          <td><b>商品合計</b></td>
          <td><%= @order.buy_total.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td><b>送料</b></td>
          <td><%= @order.shipping_cost.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td><b>請求金額合計</b></td>
          <td><b><%= @order.total_payment.to_s(:delimited) %>円</b></td>
        </tr>
      </table>
    </div>
  </div>
</div>