config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get '/genre_items' => 'items#genre_items'
    end
    resource :customers, only: [:show, :edit, :update] do
      get '/confirm' => 'customers#confirm'
      patch '/deleted' => 'customers#deleted'
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get "orders/confirm" => "orders#new"
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, except: [:new, :show]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence:true


  def cart_tax_price
    (self.item.price * 1.1).floor
  end

  def cart_subtotal
    self.cart_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :lastname, presence: true
  validates :firstname, presence: true
  validates :kana_lastname, presence: true
  validates :kana_firstname, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :email, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates:name, presence:true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  validates :name, presence:true
  validates :introduction, presence:true
  validates :price, presence:true
  validates :sale_status, inclusion: {in: [true, false] }

  has_one_attached :item_image

  def get_item_image
    (item_image.attached?) ? item_image : 'no_image.jpg'
  end

  def add_tax_price
    (self.price*1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }


  def buy_total
    buy_total = 0
    self.order_details.each do |order_detail|
      buy_total += order_detail.subtotal.to_i
    end
    return buy_total
  end

  def order_items_id
    order_items_id = []
    self.order_details.each do |detail|
      order_items_id.push(detail.item_id)
    end
    return order_items_id
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item


  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }


  def subtotal
    tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  layout 'admin_application'

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを追加しました"
      redirect_to admin_genres_path
    else
      flash[:notice] = "ジャンルを追加できませんでした"
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル名を変更しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:notice] = "ジャンル名を変更できませんでした"
      render :index
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  layout "admin_application"

  def top
    @orders = Order.order("created_at DESC").page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin_application'

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品の登録に失敗しました"
      @genres = Genre.all
      @item = Item.new
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品登録情報を変更しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品登録情報の変更に失敗しました"
      @genres = Genre.all
      @item = Item.new
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :sale_status, :item_image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  layout "admin_application"




  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details

  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      if @order.status == "入金待ち"
        @order_details.update_all(making_status: "着手不可")
      elsif @order.status == "入金確認"
        @order_details.update_all(making_status: "製作待ち")
      end
      redirect_to admin_order_path(@order)
    else
      render "show"
    end
  end



  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:lastname, :firstname, :kana_lastname, :kana_firstname, :tel, :postal_code, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:lastname, :firstname, :kana_lastname, :kana_firstname, :postal_code, :address, :tel])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#202A4B;">
    <div class="container">
      <a class="navbar-brand" href="/">
        <%= image_tag'linkedin_banner_image_1.png', size:"200x120" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown", style = "flex-wrap:wrap;">
        <ul class="navbar-nav ml-auto", style = "margin-left:55%;">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_path ,class: 'nav-link text-light border border-white rounded mr-3' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path ,class: 'nav-link text-light border border-white rounded mr-3' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light border border-white rounded' do %>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              About
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light border border-white rounded mr-3' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-light border border-white rounded' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
        <div class="search_form mt-3", style = "margin-left:50%;">
          <%= form_with method: :get, style:"width:200px;" do |f| %>
            <%= f.text_field :word, placeholder:"Search" %>
            <%= f.submit "検索", class: "btn", style:"background-color:#eee;" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_public_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#202A4B;">
    <div class="container">
      <a class="navbar-brand" href="/">
        <%= image_tag'linkedin_banner_image_1.png', size:"200x120" %>
      </a>
      <div style="color:#FFF; margin-left:200px; width:300px;">
        <% if customer_signed_in? %>
        ようこそ、<%= current_customer.lastname %>さん！
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown", style = "flex-wrap:wrap;">
        <ul class="navbar-nav ml-auto", style = "margin-left:55%;">
        <% if customer_signed_in? %>
          <li>
            <%= link_to customers_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to items_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to cart_items_path ,class: 'nav-link text-light border border-white rounded mr-3' do %>
              カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light border border-white rounded' do %>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              About
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light border border-white rounded mr-3' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-light border border-white rounded mr-3' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path ,class: 'nav-link text-light border border-white rounded' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
        <div class="search_form mt-3", style = "margin-left:37%;">
          <%= form_with method: :get, style:"width:200px;" do |f| %>
            <%= f.text_field :word, placeholder:"Search" %>
            <%= f.submit "検索", class: "btn", style:"background-color:#eee;" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f4f7f2;">
    <%= render "layouts/admin_header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f4f7f2;">
    <%= render "layouts/public_header" %>
    <%= yield %>
  </body>
</html>